Ecommerce_Project/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name="sign_up"),
    path('login/',views.login_page,name="login"),
    path('logout/',views.logout_user,name='logout'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    
]

Ecommerce_Project/App_Order/urls.py
from django.urls import path
from App_Shop import views
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/',views.add_to_cart,name="add"),
    path('cart/',views.cart_view,name="cart"),
    path('remove/<pk>/',views.remove_from_cart,name="remove"),
    path('increase/<pk>/',views.increase_cart,name="increase"),
    path('decrease/<pk>/',views.decrease_cart,name="decrease"),

]

Ecommerce_Project/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/',views.Checkout,name="checkout"),
    path('pay/',views.payment,name="payment"),
    path('payment_st/',views.payment_status,name="payment_status"),
    path('purchase/',views.purchase,name='purchase'),
    path('orders/',views.order_view,name="orders"),
    # path('status/',views.complete2,name="complete2")





]

Ecommerce_Project/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('product/<pk>/',views.ProductDetail.as_view(),name='product_detail'),


]

Ecommerce_Project/Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('',include('App_Shop.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce_Project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title_block %} Ecommerce {% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
 <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <!-- Popper JS -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <!-- Latest compiled JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link  href="https://fontawesome.com/icons/thumbs-up?style=regular">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  {% block css_block %}
  <style media="screen">
       .card {
         height : 350px;

       }
       .card-product:after {
         content :"";
         display: table;
         clear: both;
         visibility: hidden;
       }
       .card-product .price_new,  .card-product .price {
         margin-right: 5px;

       }
       .card-product .price-old {
         color : #999;
       }
       .card-product .img-wrap {
         border-radius : 3px 3px 0 0;
         overflow: hidden;
         position: relative;

       }
       .card-product .img-wrap img{
         max-height: 100%;
         max-width: 100%;
         object-fit: cover;

       }
       .card-product .info-wrap {
         overflow: hidden;
         padding: 15px;
         border-top: 1px solid #eee;
       }
       .card-product .action-wrap {
         padding-top:4px;
         margin-top:4px;
       }
       .card-product .bottom-wrap {
         padding :15px;
         border-top: 1px solid #eee;

       }
       .card-product .title {
         margin-top: 0px;

       }
     </style>


  {% endblock %}
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container" style="padding-top:15px">
      <div class="messages container mt-2">
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" area-label="Close" name="button"><span area-hidden="true">&times;</span></button>
        </div>



        {% endfor %}



        {% endif %}

      </div>

      {% block body_block %} {% endblock %}
    </div>

  </body>
</html>

Ecommerce_Project/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container">
    <a class="navbar-brand" href="{% url 'App_Shop:home' %}" >Django E-commerce Project</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expended="false" aria-label="Toggle navigation" name="button"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'App_Order:cart' %}" class="nav-link">    <i class="fa fa-shopping-cart"></i> Cart
            <span class="badge badge-light">{{request.user | cart_total }}</span>
          </a>


        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i>
            {{request.user.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'App_Login:edit_profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Order</a>
            <div class="dropdown-divider">


            </div>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>

          </div>
        </li>

        {% else %}
        <li class="nav-item">
          <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </div>

</nav>