Ecommerce_Project/App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/',views.Checkout,name="checkout"),
    path('pay/',views.payment,name="payment"),
    path('payment_st/',views.payment_status,name="payment_status"),
    path('purchase/',views.purchase,name='purchase'),
    path('orders/',views.order_view,name="orders"),
    # path('status/',views.complete2,name="complete2")





]

Ecommerce_Project/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('product/<pk>/',views.ProductDetail.as_view(),name='product_detail'),


]

Ecommerce_Project/Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('',include('App_Shop.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce_Project/App_Payment/models.py
from django.db import models

from django.conf import settings
from django.contrib.auth.models import User


class BillingAddress(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    address = models.CharField(max_length=264,blank=True)
    zipcode = models.CharField(max_length=10,blank=True)
    city = models.CharField(max_length=30,blank=True)
    country = models.CharField(max_length=20,blank=True)

    def __str__(self):
        return f'{self.user.username} Address'

    def is_fully_filled(self):
        field_name = [f.name for f in self._meta.get_fields()]

        for field_name in field_name:
            value = getattr(self,field_name)
            if value is None or value=='':
                return False
        return True
    class Meta:
        verbose_name_plural = "Billing Address"

Ecommerce_Project/App_Payment/forms.py
from django import forms
from App_Payment.models import BillingAddress
from django.views.decorators.csrf import csrf_protect

class BillingForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['address','zipcode','city','country']

Ecommerce_Project/App_Payment/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
#models and forms

from App_Order.models import Order,Cart
from App_Payment.models import BillingAddress
from App_Payment.forms import BillingForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile
from django.views.decorators.csrf import csrf_exempt


from django.contrib.auth.decorators import login_required
from django.urls import reverse

import requests
import razorpay


@login_required
def Checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    print(saved_address)
    saved_address = saved_address[0]
    print(saved_address)
    form = BillingForm(instance=saved_address)
    if request.method == "POST":
        form = BillingForm(request.POST,instance=saved_address)

        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request,f"Shipping Address Saved!")
    order_qs = Order.objects.filter(user=request.user,ordered=False)
    order_items = order_qs[0].orderitems.all()
    print(order_items[0])
    order_total = order_qs[0].get_totals()
    return render(request,'App_Payment/checkout.html',context={"form":form,"order_items":order_items,"order_total":order_total,"saved_address":saved_address})

# @login_required
# def payment2(request):
#     saved_address = BillingAddress.objects.get_or_create(user=request.user)
#     if not saved_address[0].is_fully_filled():
#         messages.info(request,f"Please complete shipping address!")
#         return redirect("App_Payment:checkout")
#     # store_id = 'mbstu616a62f185233'
#     # API_key = 'mbstu616a62f185233@ssl'
#     settings = { 'store_id': 'mbstu616a62f185233', 'store_pass': 'mbstu616a62f185233@ssl', 'issandbox': True }
#     sslcommez = SSLCOMMERZ(settings)
#     status_url = request.build_absolute_uri(reverse("App_Payment:complete2"))
#     print(status_url)
#     order_qs = Order.objects.filter(user=request.user,ordered=False)
#     order_items = order_qs[0].orderitems.all()
#     order_items_count = order_qs[0].orderitems.count()
#     order_total = order_qs[0].get_totals()
#
#     post_body = {}
#     post_body['total_amount']= Decimal(order_total)
#     post_body['currency'] = "BDT"
#     post_body['tran_id'] = "12345"
#     post_body['success_url'] = status_url
#     post_body['fail_url'] = "your fail url"
#     post_body['cancel_url'] = "your cancel url"
#     post_body['ship_name'] = current_user.user_profile.full_name
#     post_body['sessionkey'] =
#     current_user = request.user
#     post_body['cus_name'] = current_user.user_profile.full_name
#     post_body['cus_email'] = current_user.email
#     post_body['cus_phone'] = current_user.user_profile.phone
#     post_body['cus_add1'] = current_user.user_profile.address_1
#     post_body['cus_city'] = current_user.user_profile.city
#     post_body['cus_country'] = current_user.user_profile.country
#     post_body['shipping_method'] = "Courier"
#     post_body['product_name'] = order_items
#     post_body['num_of_item']= order_items_count
#
#     response = sslcommez.createSession(post_body)
#     print(response)
#     from django.shortcuts import redirect
#     return redirect(response['GatewayPageURL'])
#
#
#
#
#
#
#
#
#
#
#
#
#     # mypayment=(success_url=status_url,fail_url=status_url,cancel_url=status_url,ipn_url=status_url)
#     #
#     #
#     # mypayment.set_product_integration(total_amount=Decimal(order_total),currency='BDT',product_category='Mixed',product_name=order_items,num_of_item=order_items_count,shipping_method='Courier',product_profile='None')
#     # current_user = request.user
#     # mypayment.set_customer_info(name='current_user.user_profile.full_name',email='current_user.email',address1='current_user.user_profile.address_1',address2='current_user.user_profile.address_1',city='current_user.user_profile.city',postcode='current_user.user_profile.zipcode',country='current_user.user_profile.country',phone='current_user.user_profile.phone')
#     #
#     # mypayment.set_shipping_info(shipping_to='current_user.user_profile.full_name',address='saved_address.address_1',city='saved_address.city',postcode='saved_address.zipcode',country='saved_address.country')
#
#
#     # response_data = mypayment.init_payment()
#     # return redirect(response_data['GatewayPageURL'])
#
#     # return render(request,"App_Payment/payment2.html",context={})
#
#
#
# @login_required
# def complete2(request):
#     # if request.method == 'POST' or request.method == 'post':
#     #     payment_data =request.POST
#     #     status = payment_data['status']
#
#     render(request,"App_Payment/complete2.html",context={})
#
#







# ----------------------------------------------------










@login_required
def payment(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    if not saved_address[0].is_fully_filled():
        messages.info(request,f"Please complete shipping address!")
        return redirect("App_Payment:checkout")




    order_qs = Order.objects.filter(user=request.user,ordered=False)
    order_items = order_qs[0].orderitems.all()
    order_item_count = order_qs[0].orderitems.count()
    order_total = order_qs[0].get_totals()
    current_user = request.user
    email = current_user.email
    name = current_user.username
    phone = current_user.user_profile.phone

    order_id = order_qs[0].orderedId
    address = current_user.user_profile.address_1


    keyid = 'rzp_test_dFzwZJbvSrqAVx'

    keysecret = 'CQFSkjVl8lYMi8OAfByV18jp'

    client = razorpay.Client(auth=(keyid,keysecret))

    order_qs = Order.objects.filter(user=request.user,ordered=False)
    order_total = order_qs[0].get_totals()
    order_amount = order_total * 100
    order_currency ='BDT'
    order_receipt = 'order_rcptid_11'
    notes = {'Shipping address' : address}

    order_data = client.order.create(dict(amount=order_amount,currency=order_currency,receipt=order_receipt,notes=notes))
    print(order_data)
    order_id = order_data['id']
    order_status = order_data['status']

    return render(request,"App_Payment/payment.html",context={'order_items':order_items,'order_items_count':order_item_count,'order_amount':order_amount,'current_user':current_user,'name':name,'email':email,'order_id':order_id,'phone':phone,'keyid':keyid,'payment_st':order_data})





@login_required
def payment_status(request):
    response = request.POST
    status = True
    if status == True:
        messages.success(request,f"Your Payment Completed Successfully!")
        return HttpResponseRedirect(reverse("App_Payment:purchase"))
    else:
        messages.warning(request,f"Your Payment Failed! Please Try Again!")

    return render(request,'App_Payment/payment_status.html')

@login_required
def purchase(request):
    order_qs = Order.objects.filter(user=request.user,ordered=False)
    order = order_qs[0]
    order.ordered = True
    order.save()
    cart_items = Cart.objects.filter(user=request.user,purchased=False)
    for item in cart_items:
        item.purchased = True
        item.save()
    return HttpResponseRedirect(reverse("App_Shop:home"))

# @login_required
# def order_view(request):
#     try:
#         orders = Order.objects.filter(user=request.user,ordered=True)
#         context = {"orders": orders}
#     except:
#         messages.warning(request,"You do no have an active order")
#         return redirect("App_Shop:home")
#     return render(request,"App_Payment/order.html",context={})

@login_required
def order_view(request):
    print(request.POST)
    return render(request,"App_Payment/order.html")

Ecommerce_Project/templates/App_Payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container mt-5">
  <h2 class="mb-3">
    Shipping Address <span class="text-muted">Checkout</span>

  </h2>
  <div class="row">
    <div class="col-md-9">
      <div class="card mb-5" style="height: auto">
        <div class="card-body">
          <form method="POST">
            {{form|crispy}}
            {%csrf_token %}

            <button type="submit" name="button" class="btn btn-primary float-right">Save Address</button>


          </form>

        </div>


      </div>

    </div>
    <div class="col-md-3">
      <div class="card" style="height:auto">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            {% for order_item in order_items %}
            <li class="list-group-item">{{order_item.item.name}} X {{order_item.quentity}}</li>
            {%  endfor %}
          </ul>

        </div>
        <div class="card-footer">
          <span class="float-left"><b>Order Total</b></span>
          <span class="float-right"><b> &#2547; {{order_total|floatformat:2}}</b></span>

        </div>

      </div>
      <br><br>
      {% if saved_address.is_fully_filled %}
      <a href="{% url 'App_Payment:payment' %}" class="btn btn-warning btn-md">Make Payment</a>

      {% else %}
      <div class="alert alert-info">
        <p>Please fill up all the information to make payment.</p>

      </div>

      {% endif %}

    </div>

  </div>

</div>


{% endblock %}

Ecommerce_Project/templates/App_Payment/order.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container mt-5">
  <h2 class="text-center"><strong>Your Orders</strong></h2>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5" style="height:auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col"> #</th>
                <th scope="col">Order Id</th>
          
                <th scope="col">Amount</th>
                <th scope="col">Username</th>
              </tr>

            </thead>
            <tbody>

              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><a href="#">{{order_id}}</a></td>

                <td>{{ order_amount}}</td>
                <td>{{ name }}</td>
              </tr>


            </tbody>

          </table>

        </div>

      </div>

    </div>
    <div class="col-md-12 my-5 text-center">
      <a href="{% url 'App_Shop:home' %}">Back to Home</a>

    </div>

  </div>

</div>

{% endblock %}

Ecommerce_Project/templates/App_Payment/payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

  <h2 style="">Ecommerce Process</h2>

  <div class="container">
    <br>
    {% if payment_st %}
    <form  action="{% url 'App_Payment:payment_status' %}" method="POST">
      {% csrf_token %}
      <p>name = {{name}}</p>
      <p>keyid = {{ keyid }}</p>
      <p>order_id = {{order_id }}</p>
      <p>payment_amount = {{ order_amount }}</p>




      <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key= "{{ keyid }}"
        data-amount= "{{order_amount}} "
        data-currency="BDT"
        data-order_id="{{order_id }}"
        data-buttontext="Pay with Razorpay"
        data-name="Ecommerce Website"
        data-description="The Ecommerce website is a useful website"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name= "{{name}}"
        data-prefill.email="{{email}}"
        data-theme.color="#F37254"
    ></script>

    <input type="hidden" custom="Hidden Element" name="hidden" value="">





    </form>
    <form class="" action="{% url 'App_Payment:orders' %}" method="POST">
      {% csrf_token %}
      <p>name = {{name}}</p>
      <input id="name" type="text" name="name" value="{{ name }}">



      <p>keyid = {{ keyid }}</p>
        <input id="keyid" type="text" name="keyid" value="{{ keyid }}">
      <p>order_id = {{order_id }}</p>
      <input id="orderid" type="text" name="orderid" value="{{ order_id }}">

      <p>payment_amount = {{ order_amount }}</p>
      <input id="order_amount" type="text" name="amount" value="{{ order_amount }}">
      <input type="submit" name="" value="">


    </form>




    {% endif %}

  </div>


{% endblock %}

Ecommerce_Project/templates/App_Payment/payment_status.html
<html>
<head>
	<meta http-equiv="refresh" content="5; url = {% url 'App_Shop:home' %}">
	<title>Payment Status</title>
	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	<div class="container">
	<div class="messages container mt-2">
	{% if messages  %}
		{% for message in messages %}

		<div {% if message.tags %} class="alert alert-{{message.tags}}{{% endif %}" role="alert">

		{{message}}
		</div>
		{% endfor %}
	{% endif %}
	</div>
	</div>

</body>

</html>

{% endblock %}