Ecommerce_Project/App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up,name="sign_up"),
    path('login/',views.login_page,name="login"),
    path('logout/',views.logout_user,name='logout'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
    
]

Ecommerce_Project/App_Shop/urls.py
from django.urls import path
from App_Shop import views
app_name = 'App_Shop'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('product/<pk>/',views.ProductDetail.as_view(),name='product_detail'),


]

Ecommerce_Project/Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include('App_Shop.urls')),
    path('account/',include('App_Login.urls')),
    path('',include('App_Shop.urls')),
    path('shop/',include('App_Order.urls')),
    path('payment/',include('App_Payment.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce_Project/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_profile')
    
    full_name = models.CharField(max_length=264,blank=True)
    address_1 = models.CharField(max_length=264, blank=True)
    city = models.CharField(max_length=264 , blank=True)
    zipcode = models.CharField(max_length=10,blank=True)
    country = models.CharField(max_length=50,blank=True)
    phone = models.CharField(max_length=20,blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    profile_pic = models.ImageField(upload_to='profile_pics')

Ecommerce_Project/App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(
        required = True,
        label="",
        widget = forms.PasswordInput(attrs={'placeholder':'Password'})

    )
    password2 = forms.CharField(
        required = True,
        label = "",
        widget= forms.PasswordInput(attrs={'placeholder':'Confirm Password'})
    )

    class Meta:
        model = User
        fields = ('email','username','password1','password2')

class EditProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = "__all__"
    

Ecommerce_Project/App_Login/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponseRedirect
from django.http import HttpResponse
from App_Login.forms import CreateNewUser,EditProfile
from django.contrib.auth import authenticate, login,logout
from django.urls import reverse,reverse_lazy
from App_Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from App_Login.models import UserProfile
from App_Shop.models import Product,Category

from django.contrib import messages



def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            messages.success(request,"Account Created Successfully!")
            return HttpResponseRedirect(reverse('App_Login:login'))

    return render(request,'App_Login/sign_up.html',context={'title':'Ecommerce Website','form':form})

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('App_Shop:home'))

    return render(request,'App_Login/login.html',context={'title':'Login','form':form})

@login_required
def logout_user(request):
    logout(request)
    messages.warning(request,"You are Logout !")
    return HttpResponseRedirect(reverse('App_Shop:home'))

@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST,request.FILES,instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,"Profile Updated Successfully!")
            form = EditProfile(instance=current_user)
    return render(request,'App_Login/change_profile.html',context={'form':form})

Ecommerce_Project/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
   {% csrf_token %}
   <button type="submit" class="btn btn-warning btn-sm" name="button">Save</button>
</form>
<br>
{% endblock %}

Ecommerce_Project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock %}
{% block css_block %}
<style>
  .sign_up {
     width: 550px;
     border: 1px solid #ccc;
     padding:5px;
     border-radius:5px;

  }
  .login {
    width:550px;
    padding: 40px;
    border: 1px solid #ccc;

  }
</style>

{% endblock %}
{% block body_block %}
<center>
<div class="login">
  <form  method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button" class="btn btn-primary" style="width:100%">Login</button>


  </form>

</div>
<br>
<div class="sign_up">
  <p>Don't have an account? <a href="{% url 'App_Login:sign_up' %}">Sign up</a></p>

</div>
</center>
{% endblock %}

Ecommerce_Project/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block  %}{{title}}{% endblock %}
{% block css_block %}
<style>
  .sign_up {
     width: 550px;
     border: 1px solid #ccc;
     padding:40px;
     border-radius:5px;
  }
  .login {
    width:550px;
    padding: 5px;
    border: 1px solid #ccc;
  }
</style>
{% endblock %}
{% block body_block %}
<center>
  <div class="sign_up">
  <h3>Ecommerce Website.</h3>
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}

   <button type="submit" name="button" class="btn btn-info" style="width:100%">SignUp</button>

  </form>
</div>
<br>
<div class="login">
  <p>Have an account?<a href="{% url 'App_Login:login' %}">Login</a></p>
</div>

</center>
{% endblock %}